### ISSUE TITLE
How can we make this useful in Figma?

### ISSUE THREAD

**Issue by ebrelsford** [stamen/chartographer#19]
One of the stated goals of this tool is to contribute to a design system as created/maintained in Figma. Currently it does not do this.

There seem to be a few key ways it could help with this:
 1. Export SVGs that could be opened in Figma #11 
 2. For visualizations (like the typography chart) that cannot be exported to SVGs, consider creating a Figma plugin that can load them

@kelsey-taylor Would (2) be helpful? When you get a chance would you mind helping us define the use case here?

**Comment by mulloverit** [comment]
This issue has run its course. Might be useful to have a higher levels disucssion about carto tools for Figma, but no actions here.
