### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by kateler** [stamen/chartographer#45]
When trying to view https://chartographer.stamen.com, I get this warning: 
<img width="652" alt="image" src="https://user-images.githubusercontent.com/764181/192889022-58f6888a-649c-4df9-bff8-2386476066f2.png">

Is that URL supposed to work? I'm pretty sure it used to because I had it bookmarked.

**Comment by ebrelsford** [comment]
Yes, there was an issue with the configuration but it should work now.
