### ISSUE TITLE
Follow up on OSM slack thread about massive stylesheet

### ISSUE THREAD

**Issue by mulloverit** [stamen/chartographer#49]
Ref this [OSM slack thread](https://osmus.slack.com/archives/C01V02K52UX/p1661736268208149) about an 18K line stylesheet that borked chartographer. 

@ebrelsford is going to follow-up on the thread with the updates we've made to the tool, which should enable clean(er) handling of very large stylsheets!

**Comment by almccon** [comment]
Parent task: https://github.com/stamen/carto-tools/issues/54

**Comment by ebrelsford** [comment]
[Replied here.](https://osmus.slack.com/archives/C01V02K52UX/p1671142497368989?thread_ts=1661736268.208149&cid=C01V02K52UX)
