### ISSUE TITLE
mapbox-gl-style-recurse dependency is private GitHub repo

### ISSUE THREAD

**Issue by bdon** [stamen/chartographer#56]
It's not possible to `npm install` this repo from the outside because the repository for this dependency isn't public.

**Comment by ebrelsford** [comment]
Thanks for flagging this.

**Comment by ebrelsford** [comment]
We opened up [stamen/mapbox-gl-style-recurse](https://github.com/stamen/mapbox-gl-style-recurse) so this should be good now.

**Comment by bdon** [comment]
Thanks!
