### ISSUE TITLE
Typography chart not rendering for Mapbox style

### ISSUE THREAD

**Issue by kelsey-taylor** [stamen/chartographer#57]
## Describe the issue

I opened a style designed in Mapbox Studio in chartographer and saw some unexpected results in the typography tab:

Using Mapbox GL — nothing renders
![Screenshot 2023-03-14 at 1 57 52 PM](https://user-images.githubusercontent.com/57634568/226394408-bfad3845-e200-46fb-94e9-40fe76b76631.png)

Using Maplibre GL — only halo color renders
![Screenshot 2023-03-14 at 1 57 44 PM](https://user-images.githubusercontent.com/57634568/226394476-46df42d0-2058-4c1c-9995-13593b04ae18.png)

I tried making the style public and reuploading, but there was no change. I tried uploading a default Mapbox style (Monochrome) and had the same issue. 

## Additional context
There are a lot of error messages — would probably be easier for whoever takes this task on to try it out themselves than for me to go screenshot them all, although it looks like an access token is the main first issue.

<img width="332" alt="Screenshot 2023-03-20 at 11 54 21 AM" src="https://user-images.githubusercontent.com/57634568/226396237-62c7001e-279a-4d59-91d8-e3b32150f14f.png">

**Comment by ebrelsford** [comment]
Oh yes this is because we do not include an access token for Mapbox.

We should probably prompt the user for an access token since the style you're using might include references to sprites/glyphs/tilesets only your account has access to.

**Comment by kelsey-taylor** [comment]
Makes sense to me!
